text_extensions_for_pandas/array/arrow_conversion.py, text_extensions_for_pandas/array/test_tensor.py
This allows serialization with Arrow for TensorArray columns with multiple chunks.
Fixes #19
=> Enable chunked arrays for TensorArray serialization

text_extensions_for_pandas/array/arrow_conversion.py, text_extensions_for_pandas/array/test_tensor.py
When a TensorArray column is automatically chunked, e.g. for large array sizes, the data type is copied. In this case the type can not store the number of records as the outer dimension because this number will change as it is chunked. This removes the number of records from the shape and instead only the element shape is stored. When deserialized to numpy, the size of the Arrow extension arrow will be added to the final numpy array as the outer dimension.
Fixes #22
=> Fix for reading TensorArray column that have been automatically chunked

notebooks/CoNLL_1.ipynb, notebooks/CoNLL_2.ipynb, notebooks/CoNLL_3.ipynb, notebooks/CoNLL_4.ipynb, notebooks/CoNLL_View_Doc.ipynb, notebooks/Person.ipynb
prepend is not a valid attribute of list
This is a followup of #45
=> Use insert not prepend

config/jupyter_reqs.txt
torch and scikit-learn are used in notebooks/util.py
=> Add scikit-learn and torch to notebooks/jupyter_reqs.txt

text_extensions_for_pandas/array/tensor.py, text_extensions_for_pandas/array/test_tensor.py
This PR adds a copy constructor to the `TensorArray` class. I added tests of the copy constructor and also threw in some tests of `sum` aggregations.
=> Add copy constructor and test of sum aggregates

notebooks/CoNLL_3.ipynb, notebooks/CoNLL_4.ipynb
This code modifies the F1 score plotting code in two of the CoNLL related notebooks to generate plots that are easier to read and more consistent with each other.
Apologies for the large diff; I had to recompute the notebooks.
=> Update code for plotting F1 score

text_extensions_for_pandas/spanner/project.py, text_extensions_for_pandas/spanner/test_extract.py, text_extensions_for_pandas/spanner/test_project.py
This adds basic unit tests for the spanner extract and project modules.
Fixes #63
=> Add unit tests for spanner extract and project

notebooks/Analyze_Model_Outputs.html, notebooks/Analyze_Text.html, notebooks/Integrate_NLP_Libraries.html
This PR is an addendum to #101 with HTML versions of the notebooks.
=> Add HTML versions of notebooks from previous commit

text_extensions_for_pandas/__init__.py, text_extensions_for_pandas/array/arrow_conversion.py, text_extensions_for_pandas/array/span.py, text_extensions_for_pandas/array/tensor.py, text_extensions_for_pandas/array/test_tensor.py
Also, change function name to `span_to_arrow()` for consistency.
=> Change TensorArray dtype to TensorDtype for consistency

text_extensions_for_pandas/array/tensor.py, text_extensions_for_pandas/array/test_tensor.py
This fixes issues with TensorArray ops and enables all Pandas ops tests.
=> TensorPandas fix arithemtic and comparison ops

setup.py
PR to up the version number prior to the 0.1b1 release.
=> Increment version number to 0.1b1

setup.py
This is a minor improvement, just trying to see whether Travis CI also stops working on this repo.
=> Add classifier "Topic :: Scientific/Engineering"

.github/workflows/run_tests.yml, env.sh
This updates the initial commit of github workflow file from #154 to correctly run CI testing.
Fixes #153
=> Run github action for CI testing

MANIFEST.in
This adds the python setup MANIFEST.in file and adds files from the repo needed for packaging from source or building a conda package.
=> Adding python manifest file

README.md, docs/README.md, docs/release.md
Adding release process steps required to do the conda-forge packages, and conda installation instructions.
=> Added conda-forge release process

text_extensions_for_pandas/jupyter.py, text_extensions_for_pandas/resources/span_array.css, text_extensions_for_pandas/resources/span_array.js, text_extensions_for_pandas/test_jupyter.py
Added a wrapper object that can handle rendering multi-document SpanArrays, and restructured the initialization script to match the new render method.
=> Fixed multi-document spanarray rendering

notebooks/Analyze_Text.ipynb
removed two instances of repeated words
Signed-off-by: Patrick Culllinane <cullinap@gmail.com>
=> small grammatical updates

text_extensions_for_pandas/jupyter/span.py, text_extensions_for_pandas/resources/span_array.js
Added handling for newlines in SpanArray doctext rendering and updated the frontend's HTML sanitization with global regular expressions.
=> Handling for newlines in doctext + JS replace improvement

notebooks/Read_conllu_Files.ipynb, text_extensions_for_pandas/io/conll.py, text_extensions_for_pandas/io/test_conll.py
Addresses issue #227 , and adds regression tests to verify it.
=> Fix bug in Maybe downoad dataset; create regression tests to verify. 

MANIFEST.in, docs/release.md, setup.py
Fix for the packaging issue #231 that prevents the SpanArray visualization from working out of a stock pip install of the library. Main changes:
* Add missing resources to the `whl` file
* Add instructions to test for recurrence of #231
=> Prep for point release to fix issue #231

text_extensions_for_pandas/jupyter/span.py, text_extensions_for_pandas/jupyter/test_jupyter.py, text_extensions_for_pandas/resources/span_array.js
Patch includes LaTeX isolation in JS and additional columns for TokenSpanArrays.
Tests have been updated to reflect the new data.
Addresses issues #235 and #234
=> Patched JS handling of LaTeX and TokenSpanArray

setup.py
Minor change in preparation for new point release.
=> Increment version number and change Python version to 3.7+
