CODAIT/text-extensions-for-pandas

- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/tensor_test.py
This uses a Pandas extension base class to define comparison and arithmetic operators that are based on the internal ndarray.
> Add mixin for defining operations based on internal ndarray

- text_extensions_for_pandas/io/__init__.py
- text_extensions_for_pandas/io/test_tokenization.py
- text_extensions_for_pandas/io/tokenization.py
Add function `make_bert_tokens` to wrap a huggingface `PreTrainedTokenizerFast` tokenizer and return result as a Pandas DataFrame that includes all data from the tokenizer with character span, and token span columns.
> Add wrapper function for BERT tokenization

- text_extensions_for_pandas/array/arrow_compat.py
- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
Add Arrow extension for TensorArray and conversion function to support IO from a DataFrame. Currently, Feather format is working but Parquet has an error when reading back.
> Add arrow extension type for TensorArray IO

- notebooks/CoNLL_1.ipynb
- notebooks/CoNLL_2.ipynb
- notebooks/CoNLL_3.ipynb
- text_extensions_for_pandas/io/conll.py
The IOB2 format is what is being used, change references to indicate that along with links to wikipedia entry https://en.wikipedia.org/wiki/Inside%E2%80%93outside%E2%80%93beginning_(tagging).
> Change IOB references to indicate IOB2 format

- requirements.txt
- setup.py
This adds dependent packages from requirements.txt to setup.py so that when the user installs, the required dependencies will be installed also.
> Add dependent packages from requirements to setup.py

- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
TensorArray slices that are empty have to be handled differently to return an empty np.array
Fixes #16
> Fix for TensorArray slices that are empty

- text_extensions_for_pandas/array/arrow_compat.py
- text_extensions_for_pandas/array/arrow_conversion.py
- text_extensions_for_pandas/array/char_span.py
- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_char_span.py
- text_extensions_for_pandas/array/test_token_span.py
- text_extensions_for_pandas/array/token_span.py
Add Arrow conversions to/from char and token span arrays to enable saving DataFrames with these columns to feather files. This first implementation is not optimized for storage space and will save target text in the field metadata, possibly duplicated. Also, TokenSpanArrays will save a duplicate of the dependent CharSpanArrays in the same struct column. These could be improved in followup changes.
> Implement Arrow conversions for char and token span arrays

- text_extensions_for_pandas/test_util.py
- text_extensions_for_pandas/util.py
Bug fix for issue #31 
Avoids the issue where double dollar signs inside of text are interpreted by the math rendering system built into Jupyter as LaTeX inline math delimiters, causing improper rendering of text. @frreiss
> Added workaround to avoid double dollar signs not rendering properly

- .gitignore
- .travis.yml
- config/dev_env.yml
- config/dev_env_forge.yml
- config/dev_reqs.txt
- config/jupyter_reqs.txt
- env.sh
This PR refactors the Anaconda environment setup code in `env.sh` so that the environment will be the same between developers' machines and Travis CI runs. I have moved all the lists of dependencies for development, testing, and Jupyter into config files (commit 38f6e7a). I have also updated the Travis config file so that it uses `env.sh` to build the local environment (commit 905ae63). I may back out of that change if Travis has trouble testing this PR.
I also modified `.gitignore` so that Vim swap files won't get picked up by `git status` (commit 78dc08c)
> Refactor environment setup code

- config/dev_reqs.txt
- text_extensions_for_pandas/io/tokenization.py
The latest version of the [Transformers library](https://huggingface.co/transformers/) moved the `PreTrainedTokenizerFast` class to a new location within the package. This change breaks our integration with that project's tokenizer.
This PR updates the `import` statement to use the new location of `PreTrainedTokenizerFast`. I have also modified `dev_reqs.txt` to specify version 3.0.0 or greater of `transformers`.
@BryanCutler @xuhdev @ZachEichen you will want to rerun `env.sh` or manually upgrade your local copy of the `transformers` Python library after this PR is merged.
> Update BERT tokenizer integration to reflect API changes in Transformers library

- config/dev_reqs.txt
- text_extensions_for_pandas/io/test_conll.py
- text_extensions_for_pandas/io/test_spacy.py
SpaCy shipped a new version of their library, with new language models that produce substantially different results even on simple text. This PR updates our regression tests to account for the latest SpaCy model changes.
I've also pinned the version of SpaCy in `dev_reqs.txt` to *exactly* 2.3.2 in the hopes that doing so will prevent this sort of thing from happening in the future.
> Fix tests again

- text_extensions_for_pandas/io/watson.py
I mistyped a function name while merging #57 . This PR contains a one-line fix for that problem.
> MINOR: Fix typo in merge of PR

- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
Add remaining hooks for TensorArray. Calling `pandas.Series.factorize` still requires `_values_for_factorize` to be implemented.
> Implement remaining hooks for TensorArray

- requirements.txt
- text_extensions_for_pandas/array/arrow_conversion.py
- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_arrow_conversion.py
This adds `__arrow_ext_class__` to `ArrowTensorType` so that an extension array of that type will get the class attributes. Moved conversion of chunked tensor arrays to `arrow_to_tensor_array`, which is consistent with CharSpanArray and TokenSpanArray conversions. Also added `test_arrow_conversions` to test out arrow directly.
> Improvements to ArrowTensorArray to make consistent

- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
This wraps a single row np.ndarray from a `TensorArray` in a `TensorElement` class. Pandas does internal checks after getting single rows and fails if they are np.ndarray because it expects a length of 1, but gets something different. TensorArray and TensorElement also now implement the `__array__` interface which allows creating a numpy array automatically through numpy apis. For example, below will produce a np.ndarray of shape (3,) with dtype np.int64
```
arr = np.array(TensorArray([1, 2, 3]))
```
> Use TensorElement for single row of TensorArray

- .travis.yml
- text_extensions_for_pandas/__init__.py
- text_extensions_for_pandas/io/__init__.py
- text_extensions_for_pandas/io/test_bert.py
- text_extensions_for_pandas/io/watson/__init__.py
- text_extensions_for_pandas/io/watson/tables.py
Fixed imports causing problems with Python 3.6. Import in the form of `import text_extensions_for_pandas.io.bert as bert` end up causing a circular reference due to later imports also referencing `io` which has not been initialized yet. Using the form `from text_extensions_for_pandas.io import bert` avoid this.
> Fixes for Python 3.6

- README.md
- binder/postBuild
This PR adds the necessary configuration files and links to run our example notebooks on Binder. 
I've also added links to the README.md file. For now, the links point to the source branch for this PR. After these changes are merged, I'll update the links in the README.md in the master branch to point to master.
> Support for running notebooks on Binder

- text_extensions_for_pandas/array/tensor.py
Removing the contiguous option in the TensorArray constructor. It's not needed, except for the Arrow conversion and is already forced there, and to be used properly would need to propagate when making a new TensorArray from an existing one.
> Remove TensorArray contiguous option

- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
TensorArray.isna() used numpy functions only for numeric types. This change adds checks for numpy objects and strings.
Fixes #132
> Fix TensorArray.isna() to handle types other than numeric

- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
`TensorArray` aggregations were producing a ndarray of `TensorArray`s for each group. This changes aggs to produce a `TensorElement` as a scalar, then allow construction of a new `TensorArray` using an ndarray of the resulting `TensorElement` objects.
Fixes #124
> Fix TensorArray aggregations that produce ndarray of objects

- .travis.yml
- README.md
- config/dev_env.yml
- env.sh
This PR should hopefully fix the issues we've been having with CI builds hanging.
I've added proper argument-handling code to `env.sh`, and I've fixed a bug that caused that script to hang if the `PANDAS_VERSION` environment variable is set.
`env.sh` now looks for an environment variable `PYTHON_VERSION` (there's also a command-line argument `--python_version` for non-Travis use) and installs the specified version of Python.
I've updated all the Travis builds to use the `PYTHON_VERSION` environment variable, and I've added an additional build for Python 3.8.
> Fix CI issues

- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
Adding convenience methods to get numpy properties, so it's not necessary to convert using `to_numpy()`.
> Add TensorArray numpy properties for dtype, ndims and shape

- notebooks/Analyze_Text.ipynb
- test_data/io/test_watson/mentions_response.txt
- text_extensions_for_pandas/io/watson/nlu.py
- text_extensions_for_pandas/io/watson/test_nlu.py
- text_extensions_for_pandas/io/watson/util.py
This PR implements the feature described in #54.
I've added code to `nlu.py` to unroll the nested information that NLU returns about entity mentions into a DataFrame with one row per entity mention. After my modifications, the `parse_response()` method returns a dictionary with an additional key "entity_mentions" that points to the new DataFrame. If the user didn't tell NLU to extract entity mentions, this DataFrame will be empty but will still be present.
I added some new tests to cover the new functionality. I also updated the main NLU-related notebook with some Markdown to explain what's stored under the "entity_mentions" key in the return value of `parse_response()`.
> Add code to convert NLU entity mentions information to a DataFrame

- .github/workflows/run_tests.yml
- requirements.txt
- text_extensions_for_pandas/array/span.py
- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_span.py
- text_extensions_for_pandas/array/test_tensor.py
- text_extensions_for_pandas/array/test_token_span.py
- text_extensions_for_pandas/io/watson/test_tables.py
There are a number of test failures when using Pandas 1.2.0.
* The method `pandas.core.ops._get_op_name()` has been removed in Pandas >=1.2.0. This was being used when building `TensorArray` ops, and is replaced with similar usage in `ExtensionScalarOpsMixin`.
* `TensorArray` should return it's instance when `astype()` called with same type
* `TensorArray._contains_` needs to have proper implementation of `any()`
* `repr()` is broken when using float values of ndims > 2
Fixes #158
> Fix test failures with Pandas 1.2.0

- text_extensions_for_pandas/array/span.py
- text_extensions_for_pandas/array/token_span.py
- text_extensions_for_pandas/spanner/join.py
- text_extensions_for_pandas/spanner/test_join.py
- text_extensions_for_pandas/util.py
The current implementation of `tp.spanner.overlap_join` crashes while computing shingle lengths if both inputs are empty. This PR fixes this problem.
I have added regression tests for the case that triggered the original crash, as well as a number of other combinations of empty/non-empty inputs, plus combinations of character-based and token-based span arrays.
I also encountered and fixed a minor bug in the way that the constructors for `SpanArray` and `TokenSpanArray` handle empty Python lists of begin and end offsets.
> Handle corner cases involving empty inputs to overlaps/contains join

- text_extensions_for_pandas/array/span.py
- text_extensions_for_pandas/array/test_span.py
- text_extensions_for_pandas/array/token_span.py
This PR adds a "first" reduction (aka aggregate) to `SpanArray` and `TokenSpanArray`. I've also implemented the `na_value()` hook on the associated dtype classes, so that empty groups in a `groupby` expression will get a reasonable value.
There is still some work to be done in handling the case where someone tries to roll up a list of `Span` objects, some of which are null values with null target text and some of which aren't, into a single `SpanArray`. I think that problem is best handled in a follow-on PR.
> Add "first" reduction type and NA value to spans

- text_extensions_for_pandas/array/span.py
- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/token_span.py
Fixed `_from_sequence` to handle np.nan, added `__contains__` to check for null values with text set to `None`.
Closes #168
> Fixes for use with Pandas 1.2.1

- text_extensions_for_pandas/array/span.py
- text_extensions_for_pandas/array/test_span.py
In the addition operation, the span should return NotImplemented to allow Pandas to unwrap
> Fixed bug when adding spans from a series

- text_extensions_for_pandas/array/arrow_conversion.py
- text_extensions_for_pandas/array/test_span.py
- text_extensions_for_pandas/array/thing_table.py
This changes Arrow serialization for SpanArray to store documents in a dictionary that is indexed by text ids. Also added support for saving to Parquet files.
From #179
> Fix Arrow serializaiton for SpanArray multidoc support

- text_extensions_for_pandas/array/arrow_conversion.py
- text_extensions_for_pandas/array/test_token_span.py
This fixes Arrow conversion of a TokenSpanArray that possibly uses multiple SpanArrays with multiple documents. The conversion follows these steps:
1. Get SpanArrays used in the TokenSpanArray and convert these to arrow, each is a struct with begins, ends, and dictionary array with the document
2. Concat the arrow SpanArrays together to make an arrow list of them
3. Build an arrow dictionary array that maps the index of the SpanArray used by each element of the TokenSpanArray to the SpanArray in the arrow list
4. create a struct array with token begins, token ends, and the token dictionary array
> [WIP] Fix Arrow conversion for TokenSpanArray with multi-doc

- text_extensions_for_pandas/array/arrow_conversion.py
- text_extensions_for_pandas/array/test_token_span.py
Adds raising of error for pyarrow < 2 due to unsupported use of nested dictionary arrays.
This also adds support for TokenSpan array containing null values.
Currently disable TokenSpan for multi-doc due to unsupported pyarrow.concat with dictionary unification.
Closes #179
> Raise error for TokenSpan arrow conversion with pyarrow < 2

- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
This implements the `__array_ufunc` method in `TensorArray` for better integration with NumPy. When TensorArrays are used with numpy universal functions, such as `np.add()`, this method will be invoked to unwrap the inputs then wrap back the output as a TensorArray.
> Adding NumPy ufunc to TensorArray

- setup.py
While doing some internal testing, I discovered that we didn't update the Python version in `setup.py` when we added Python 3.6 support. This PR updates the package metadata to indicate that this library runs on Python 3.6.
> Expand supported Python versions to cover 3.6 and increment package version

- text_extensions_for_pandas/spanner/extract.py
- text_extensions_for_pandas/spanner/test_extract.py
While working on a blog post, I noticed that we are missing some variants of the `extract` operator from spanner algebra:
* `extract_regex`: return all matches of a character-based regex
* `extract_split`: Split the document into spans according to a set of split points
This PR implements those two operations and adds appropriate tests.
> Add some missing extract ops

- text_extensions_for_pandas/jupyter.py
- text_extensions_for_pandas/resources/span_array.css
- text_extensions_for_pandas/resources/span_array.js
For issue #202
Added interactivity to the JS-generated HTML rendering of SpanArrays and TokenSpanArrays, including table controls like visibility toggling and highlight locking. 
Removed JupyterLab-specific CSS overrides in favor of more consistent styling across themes, and made some general styling adjustments.
Added highlights as a view instance property, preserving highlight locks over multiple view renders, but isolating the locks to the instance (Multiple JPL windows of the same notebook can have separate Spans hidden or highlighted at the same time).
Compatibility verified in JupyterLab and VSCode
> SpanArray HTML rendering interactivity and view instance tools

- text_extensions_for_pandas/array/span.py
- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/test_tensor.py
- text_extensions_for_pandas/array/token_span.py
Pandas 1.3.x renamed its abstract base class for indexes from `ABCIndexClass` to `ABCIndex`, which is messing up some of our type checks. This PR adds some logic to work around that renaming. I'm using exceptions as control flow, which is a bit ugly, but the alternatives are also ugly.
> Fix failing tests with Pandas 1.3.0 (was: Add logic to deal with ABCIndexClass being renamed to ABCIndex)

- text_extensions_for_pandas/array/span.py
- text_extensions_for_pandas/array/tensor.py
- text_extensions_for_pandas/array/token_span.py
Follow-on PR that makes some suggested changes from @BryanCutler's review on #218.
> Minor: Address review comments from #218

- text_extensions_for_pandas/array/test_token_span.py
- text_extensions_for_pandas/array/token_span.py
This follow-on PR fixes a minor problem in the fix for `TokenSpanArray.is_single_document` from #218.
> Fix regression from PR #218

- env.sh
Recent versions of Anaconda don't install `pip` by default in new environments. This causes problems when our environment setup script tries to run `pip install` from inside a newly-created environment. This PR adds `pip` to the initial environment contents to fix this problem.
> Add pip to initial environment contents

- text_extensions_for_pandas/array/tensor.py
The discussion around https://github.com/pandas-dev/pandas/issues/42430 is taking longer than expected. Pandas has released a 1.3.1 release without a fix for this issue. From the direction the discussion is taking, it looks like further performance related changes are likely to introduce similar breakage in the future, even after this issue is patched.
This PR removes the Pandas version check from the workaround from this issue. That way we won't be broken if Pandas decides to put the offending performance code into another future release. Due to the other checks that are still done, the workaround is still only activated in a narrow set of circumstances even after this change.
> Remove version check from workaround for Pandas #42430

- text_extensions_for_pandas/io/conll.py
- text_extensions_for_pandas/io/test_conll.py
This PR adds a bug fix from [Zach's research branch](https://github.com/ZachEichen/text-extensions-for-pandas/tree/corpus-cleaning-tests). The fix addresses an issue when reading the EWT corpus with SRL annotations in CoNLL-U format.
> Bug fix for SRL import from Zach's branch.

- text_extensions_for_pandas/jupyter/widget/core.py
- text_extensions_for_pandas/spanner/__init__.py
- text_extensions_for_pandas/spanner/extract.py
This PR includes a few minor fixes.
* Update a null check in the DataFrame widget code to use `is not None` instead of casting to bool
* Add some missing symbols in the `spanner` module
* Fix docstrings in the `spanner` module.
> Minor fixes

- .github/workflows/run_tests.yml
- config/dev_reqs.txt
- env.sh
This PR updates the versions of Python we use in the CI flows, so as to unblock #251
> Update Python version for CI
